### ISSUE TITLE
Translation and modified field

### ISSUE THREAD

**Issue by juniogro10** [sharish/CreditCardView#1]
Hello,
How do I modify the size of the card name field?
How can I translate all fields?
![fotocard](https://cloud.githubusercontent.com/assets/8702753/13437969/958dc03a-dfc5-11e5-81bb-5c9f8618e8bb.png)

The buttons i can put
  
![libcard](https://cloud.githubusercontent.com/assets/8702753/13437797/d3d0459e-dfc4-11e5-8971-c161ae83aed2.jpg)

Sorry for the english ..

Thanks..

**Comment by cooltechworks** [comment]
1. Can you tell me why to reduce the size of the fields? For now you can fork this repo and modify it.
2. For translations, you can create localisation string.xml and put them in respective resource folders for the required language and send me a pull request and I will merge. In your case of Portuguese, create a resource folder as below

for Portugal Portuguese
```
 res
  --- values-pt_PT
         ------strings.xml
```

for Brazil Portuguese
```
 res
  --- values-pt_BR
         ------strings.xml
```

**Comment by juniogro10** [comment]
1.
The size of the field does not accept my name.
Example of my name on card: XXXXXXXX X XXXX XX or XXXXXXXX X X XXXXXX 
X = my name.
It is not accepted.
I will fork for modification.

2.
ok

Thanks..
