### ISSUE TITLE
Unable to sync the dependency

### ISSUE THREAD

**Issue by brianbaliat** [sharish/CreditCardView#13]
keep saying try again . android studio 2.2.1

**Comment by sharish** [comment]
@brianbaliat You might have missed to add jitpack maven reference in your gradle. Kindly add

```
repositories {
    jcenter()
    maven { url "https://jitpack.io" }
}
```

If that was not the issue, I will be in need of your build.gradle file to find out the issue.

Thanks,
Harish

**Comment by sharish** [comment]
Re-open the issue if you still have troubles syncing the project.

Thanks,
Harish
