### ISSUE TITLE
4 digit CVV

### ISSUE THREAD

**Issue by dalwadi2** [sharish/CreditCardView#26]
I have card with 4 digit CVV, now library doesn't allow me to put 4 digits.can you help me ? is there any function to set dynamic CVV size ?

**Comment by sharish** [comment]
Next version will allow you to do that.

Thanks,
Harish

**Comment by dalwadi2** [comment]
may I know the next version?
it's important for me, so please respond ASAP
thanks

**Comment by sharish** [comment]
Next week. #21 PR has the changes related this issue which needs to verified and released along with other changes.

**Comment by dalwadi2** [comment]
okay thanks.
when you upload new version than and then close this issue so I'll notified that you've released new version.
thanks again.

**Comment by sharish** [comment]
Fixed in v1.0.3.



With the github handle change, the new dependency line in build.gradle will be 

```gradle
compile 'com.github.sharish:CreditCardView:v1.0.3'
```
and not 
<strike>
compile 'com.github.cooltechworks:CreditCardView:v1.0.3'
</strike>


Thanks,
Harish
