### ISSUE TITLE
In creditcard view each editext field is half cut.

### ISSUE THREAD

**Issue by ZeroCool00** [sharish/CreditCardView#27]
![screenshot_20170106-123803](https://cloud.githubusercontent.com/assets/18139594/21710265/892d38ce-d40d-11e6-92f5-770a628ba865.png)
![screenshot_20170106-123816](https://cloud.githubusercontent.com/assets/18139594/21710266/892ebd52-d40d-11e6-94fc-18f0a80f20b3.png)

**Comment by sharish** [comment]
Fixed in v1.0.3.



With the github handle change, the new dependency line in build.gradle will be 

```gradle
compile 'com.github.sharish:CreditCardView:v1.0.3'
```
and not 
<strike>
compile 'com.github.cooltechworks:CreditCardView:v1.0.3'
</strike>


Reopen if not fixed.

Thanks,
Harish

**Comment by ZeroCool00** [comment]
thank you for your response. its fix now.

**Comment by ZeroCool00** [comment]
now there is no next or previous button. its disappear now. plz fix it.
