### ISSUE TITLE
Next and previous button is missing in creditcard

### ISSUE THREAD

**Issue by ZeroCool00** [sharish/CreditCardView#29]
i m writing another issue cause i m not able to reopen my previous issue. 
[text half cut](https://github.com/sharish/CreditCardView/issues/27) in this issue you suggest me use different dependency, but there is no next and previous button.

My text half cut problem is solved but now i m not able to get data from credit card because of missing done button.

![screenshot_20170117-101333](https://cloud.githubusercontent.com/assets/18139594/22008218/2f6d3a88-dc9f-11e6-867d-8621fedbd46f.png)

**Comment by sharish** [comment]
Use version v1.0.4 

Thanks,
Harish

**Comment by ZeroCool00** [comment]
Thanks man.. i got quick solution today..  this is very useful lib.

**Comment by tag2biswa** [comment]
after adding multiple numbers of credit card, and again pressing back to close the application. the added cards are getting removed and the app is opening as fresh loaded...How to address this problem
