### ISSUE TITLE
Indicating credit card type in CreditCardView if you don't know the full credit card number

### ISSUE THREAD

**Issue by jacobilin** [sharish/CreditCardView#39]
Hi guys, 

When our data comes from the server I know only the card type ("VISA", "AMEX", "Master Card") and the last 4 digit of the card.

Is there any way to indicate the card's type in CreditCardView without knowing the full credit card number?

Thanks in advance!

**Comment by sharish** [comment]
Not possible. Your server either needs to specify the type of card directly or it should send first few digits of the credit card number so as you can find the type of card based on the logic given here

http://www.regular-expressions.info/creditcard.html

Thanks,
Harish
