### ISSUE TITLE
Could not GET 'https://jitpack.io/com/github/sharish/CreditCardCheckoutView/v1.0.4/CreditCardCheckoutView-v1.0.4.pom'. Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by amsterdatech** [sharish/CreditCardView#42]
Could not GET 'https://jitpack.io/com/github/sharish/CreditCardCheckoutView/v1.0.4/CreditCardCheckoutView-v1.0.4.pom'. Received status code 401 from server: Unauthorized

This could be due to an outage or in case remote repository become private or been deleted.

Any mainteiners here?

**Comment by sharish** [comment]
It is https://jitpack.io/com/github/sharish/CreditCardView/v1.0.4/CreditCardView-v1.0.4.pom

The name of the repo is CreditCardView and not CreditCardCheckoutView. Kindly recheck.

Thanks,
Harish

**Comment by amsterdatech** [comment]
Thanks I made a mistake during refactoring and undesirable occurrences has been changed.
I fix it and everything is currently working.

Thanks,
William
